# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190425_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='store',
            field=models.IntegerField(null=True),
        ),
    ]
