# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-25 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190425_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_movie',
            field=models.ManyToManyField(to='boards.category'),
        ),
    ]
