# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20190425_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='static/image/movie_default', upload_to='static/image'),
        ),
    ]
