# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-25 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190425_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='static/image/movie_default.png', upload_to='static/image'),
        ),
    ]
