# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-25 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190425_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='store',
            new_name='score',
        ),
    ]
